version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.1.1

workflows:
  web:
    jobs:
      - build-web:
          filters:
            branches:
              only:
                - main
                - develop
                - derhabicht/1/deployment
      - deploy-web:
          filters:
            branches:
              only:
                - main
                - derhabicht/1/deployment
          requires:
            - build-web
jobs:
  build-web:
    working_directory: ~/wendover/web
    docker:
      - image: cimg/node:21.6.2
    steps:
      - checkout:
          path: ~/wendover
      - restore_cache:
          key: dependency-cache{{ checksum "yarn.lock" }}
      - run:
          name: install-packages
          command: yarn install
      - save_cache:
          key: dependency-cache{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: build-project
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - ./dist
  deploy-web:
    working_directory: ~/wendover/web
    docker:
      - image: cimg/base:2024.02
    steps:
      - attach_workspace:
          at: .
      - aws-s3/sync:
          from: ./dist
          to: ${WENDOVER_WEB_BUCKET}
          arguments:
            --acl public-read \
            --cache-control "max-age=86400"

#  build-wendsrv:
#    docker:
#      - image: cimg/base:2024.02
#    steps:
#      - checkout
#      -